[package]
name = "RustOS"
version = "0.0.2"
edition = "2018"
authors = ["commandcontrolQ"]

[dependencies]
bootloader = "0.9.8"
volatile = "0.2.6"
spin = "0.5.2"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
